[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Proxy settings for local dev
[[redirects]]
  from = "/api/proxy/*"
  to = "http://160.191.243.253:8003/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/*"
  to = "http://160.191.243.253:8003/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200