[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/api/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Content-Type, Authorization, Accept", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Additional security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.cloudinary.com api.cloudinary.com *.netlify.app; img-src 'self' data: blob: *.cloudinary.com; connect-src 'self' *.netlify.app http://160.191.243.253:8003;"